spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/pearsmatch
spring.datasource.username=chenwang
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=change-this-to-a-long-secret-key-for-development-only-123456789
jwt.expiration-ms=86400000